# Generated by Django 5.2.4 on 2025-10-02 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Faktura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numer", models.CharField(max_length=50)),
                ("data_wystawienia", models.DateField()),
                ("kwota_netto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("kwota_vat", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "rodzaj",
                    models.CharField(
                        choices=[
                            ("przychodowa", "Przychodowa"),
                            ("kosztowa", "Kosztowa"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
