# Generated by Django 5.2.4 on 2025-10-03 09:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vat_simulation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faktura",
            name="kwota_netto",
        ),
        migrations.RemoveField(
            model_name="faktura",
            name="kwota_vat",
        ),
        migrations.AddField(
            model_name="faktura",
            name="adres_siedziba",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="faktura",
            name="data_sprzedazy",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name="faktura",
            name="kontrahent",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="faktura",
            name="netto_23",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="faktura",
            name="netto_8",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="faktura",
            name="plik_pdf",
            field=models.FileField(default="-", upload_to="faktury_pdfs/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faktura",
            name="suma_brutto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="faktura",
            name="suma_netto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="faktura",
            name="suma_vat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="faktura",
            name="typ",
            field=models.CharField(
                choices=[("sprzedazowa", "Sprzedażowa"), ("kosztowa", "Kosztowa")],
                default="-",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faktura",
            name="vat_23",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="faktura",
            name="vat_8",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="faktura",
            name="wart_brutto_23",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="faktura",
            name="wart_brutto_8",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="faktura",
            name="rodzaj",
            field=models.CharField(
                choices=[("sprzedazowa", "Sprzedażowa"), ("kosztowa", "Kosztowa")],
                max_length=20,
            ),
        ),
    ]
