# Generated by Django 5.2.4 on 2025-10-04 14:23

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_alter_invoice_invoice_type"),
        (
            "vat_simulation",
            "0002_remove_faktura_kwota_netto_remove_faktura_kwota_vat_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="faktura",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoices.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="faktura",
            name="data_sprzedazy",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
