# Generated by Django 5.2.4 on 2025-10-21 17:02

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_alter_invoice_user"),
        ("vat_simulation", "0003_faktura_invoice_alter_faktura_data_sprzedazy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sprzedazowa", "Sprzedażowa"),
                            ("kosztowa", "Kosztowa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="faktury_pdfs/")),
                ("numer", models.CharField(max_length=50)),
                ("data_wystawienia", models.DateField()),
                ("data_sprzedazy", models.DateField(default=datetime.date.today)),
                ("kontrahent", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "adres_siedziba",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "wart_brutto_23",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vat_23",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "netto_23",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "wart_brutto_8",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vat_8",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "netto_8",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "suma_netto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "suma_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "suma_brutto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rodzaj",
                    models.CharField(
                        choices=[
                            ("sprzedazowa", "Sprzedażowa"),
                            ("kosztowa", "Kosztowa"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="invoices.invoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vat_simulation_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Faktura",
        ),
    ]
