# Generated by Django 5.2.4 on 2025-10-21 23:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_alter_invoice_user"),
        ("vat_simulation", "0005_faktura_delete_invoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Faktura",
            new_name="BillingRecord",
        ),
    ]
