# Generated by Django 5.2.4 on 2025-09-23 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nazwa firmy"
                    ),
                ),
                (
                    "nip",
                    models.CharField(blank=True, max_length=20, verbose_name="NIP"),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Adres siedziby firmy"),
                ),
                (
                    "legal_form",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Forma prawna firmy"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data rozpoczęcia działalności",
                    ),
                ),
                (
                    "regon",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Numer REGON"
                    ),
                ),
                (
                    "vat_registered",
                    models.BooleanField(
                        default=False, verbose_name="Rejestracja na VAT"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
