# Generated by Django 5.2.4 on 2025-10-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="vat_period",
            field=models.CharField(
                choices=[("monthly", "Miesięczny"), ("quarterly", "Kwartalny")],
                default="monthly",
                max_length=20,
                verbose_name="Okres rozliczeniowy VAT",
            ),
        ),
    ]
