# Generated by Django 5.2.3 on 2025-09-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data rozpoczęcia działalności"
            ),
        ),
    ]
