# Generated by Django 5.2.4 on 2025-10-02 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_start_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
